// Copyright The TBox Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// Metadata defines all possible metadata for objects.
// For example, for stream of dataChunks, is used to represent:
//   - chunk header,
//   - data descriptions,
//   - data encoding descriptions,
//   - etc.
// Can also be used as metadata description for any other objects.
// Since protobuf has ability not to send 'optional' fields, metadata can have full set of fields, describing
// all possible metadata options and have only few of them which are really used sent to the correspondent.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: api/common/data_chunk_properties.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataChunkProperties specifies properties of a DataChunk
type DataChunkProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Digest represents digest of the object. [Optional]
	Digest *Digest `protobuf:"bytes,100,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	// Offset represents offset of the object within the stream. [Optional]
	Offset *int64 `protobuf:"varint,200,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	// Len represents length of the object. [Optional]
	Len *int64 `protobuf:"varint,300,opt,name=len,proto3,oneof" json:"len,omitempty"`
	// Total represents total length of the object. [Optional]
	Total *int64 `protobuf:"varint,400,opt,name=total,proto3,oneof" json:"total,omitempty"`
	// Last identifies last object within the stream. Optional
	Last *bool `protobuf:"varint,500,opt,name=last,proto3,oneof" json:"last,omitempty"`
}

func (x *DataChunkProperties) Reset() {
	*x = DataChunkProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_common_data_chunk_properties_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (*DataChunkProperties) ProtoMessage() {}

func (x *DataChunkProperties) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_data_chunk_properties_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunkProperties.ProtoReflect.Descriptor instead.
func (*DataChunkProperties) Descriptor() ([]byte, []int) {
	return file_api_common_data_chunk_properties_proto_rawDescGZIP(), []int{0}
}

func (x *DataChunkProperties) GetDigest() *Digest {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *DataChunkProperties) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *DataChunkProperties) GetLen() int64 {
	if x != nil && x.Len != nil {
		return *x.Len
	}
	return 0
}

func (x *DataChunkProperties) GetTotal() int64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *DataChunkProperties) GetLast() bool {
	if x != nil && x.Last != nil {
		return *x.Last
	}
	return false
}

var File_api_common_data_chunk_properties_proto protoreflect.FileDescriptor

var file_api_common_data_chunk_properties_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe3, 0x01,
	0x0a, 0x13, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18,
	0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x64, 0x69, 0x67,
	0x65, 0x73, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0xc8, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x03, 0x6c, 0x65, 0x6e, 0x18, 0xac, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x02, 0x52, 0x03, 0x6c, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x90, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x03, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x18, 0x0a, 0x04, 0x6c, 0x61, 0x73, 0x74,
	0x18, 0xf4, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x04, 0x52, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x88,
	0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6c, 0x65, 0x6e,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6c,
	0x61, 0x73, 0x74, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x6c, 0x79, 0x2d, 0x69, 0x6f, 0x2f, 0x61, 0x74, 0x6c,
	0x61, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_common_data_chunk_properties_proto_rawDescOnce sync.Once
	file_api_common_data_chunk_properties_proto_rawDescData = file_api_common_data_chunk_properties_proto_rawDesc
)

func file_api_common_data_chunk_properties_proto_rawDescGZIP() []byte {
	file_api_common_data_chunk_properties_proto_rawDescOnce.Do(func() {
		file_api_common_data_chunk_properties_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_common_data_chunk_properties_proto_rawDescData)
	})
	return file_api_common_data_chunk_properties_proto_rawDescData
}

var file_api_common_data_chunk_properties_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_common_data_chunk_properties_proto_goTypes = []interface{}{
	(*DataChunkProperties)(nil), // 0: api.common.DataChunkProperties
	(*Digest)(nil),              // 1: api.common.Digest
}
var file_api_common_data_chunk_properties_proto_depIdxs = []int32{
	1, // 0: api.common.DataChunkProperties.digest:type_name -> api.common.Digest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_common_data_chunk_properties_proto_init() }
func file_api_common_data_chunk_properties_proto_init() {
	if File_api_common_data_chunk_properties_proto != nil {
		return
	}
	file_api_common_digest_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_common_data_chunk_properties_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataChunkProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_common_data_chunk_properties_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_common_data_chunk_properties_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_data_chunk_properties_proto_goTypes,
		DependencyIndexes: file_api_common_data_chunk_properties_proto_depIdxs,
		MessageInfos:      file_api_common_data_chunk_properties_proto_msgTypes,
	}.Build()
	File_api_common_data_chunk_properties_proto = out.File
	file_api_common_data_chunk_properties_proto_rawDesc = nil
	file_api_common_data_chunk_properties_proto_goTypes = nil
	file_api_common_data_chunk_properties_proto_depIdxs = nil
}
