// Copyright The TBox Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// Digest represents abstract digest of multiple types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: api/common/digest.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DigestType represents all types of digests in the system.
type DigestType int32

const (
	// Due to first enum value has to be zero in proto3
	DigestType_DIGEST_RESERVED DigestType = 0
	// Unspecified means we do not know its type
	DigestType_DIGEST_UNSPECIFIED DigestType = 100
	// MD5 digest
	DigestType_DIGEST_MD5 DigestType = 200
	// SHA256 digest
	DigestType_DIGEST_SHA256 DigestType = 300
)

// Enum value maps for DigestType.
var (
	DigestType_name = map[int32]string{
		0:   "DIGEST_RESERVED",
		100: "DIGEST_UNSPECIFIED",
		200: "DIGEST_MD5",
		300: "DIGEST_SHA256",
	}
	DigestType_value = map[string]int32{
		"DIGEST_RESERVED":    0,
		"DIGEST_UNSPECIFIED": 100,
		"DIGEST_MD5":         200,
		"DIGEST_SHA256":      300,
	}
)

func (x DigestType) Enum() *DigestType {
	p := new(DigestType)
	*p = x
	return p
}

func (DigestType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_digest_proto_enumTypes[0].Descriptor()
}

func (DigestType) Type() protoreflect.EnumType {
	return &file_api_common_digest_proto_enumTypes[0]
}

func (x DigestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DigestType.Descriptor instead.
func (DigestType) EnumDescriptor() ([]byte, []int) {
	return file_api_common_digest_proto_rawDescGZIP(), []int{0}
}

// Digest represents abstract digest.
type Digest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Type of the digest. MD5 or SHA256 or something else
	Type DigestType `protobuf:"varint,100,opt,name=type,proto3,enum=api.common.DigestType" json:"type,omitempty"`
	// Data. Any arbitrary sequence of bytes no longer than 2^32
	Data []byte `protobuf:"bytes,200,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Digest) Reset() {
	*x = Digest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_common_digest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (*Digest) ProtoMessage() {}

func (x *Digest) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_digest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Digest.ProtoReflect.Descriptor instead.
func (*Digest) Descriptor() ([]byte, []int) {
	return file_api_common_digest_proto_rawDescGZIP(), []int{0}
}

func (x *Digest) GetType() DigestType {
	if x != nil {
		return x.Type
	}
	return DigestType_DIGEST_RESERVED
}

func (x *Digest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_common_digest_proto protoreflect.FileDescriptor

var file_api_common_digest_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x64, 0x69, 0x67,
	0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x49, 0x0a, 0x06, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12,
	0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x67, 0x65, 0x73,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0xc8, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x2a, 0x5e, 0x0a, 0x0a, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13,
	0x0a, 0x0f, 0x44, 0x49, 0x47, 0x45, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x45, 0x52, 0x56, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x44, 0x49, 0x47, 0x45, 0x53, 0x54, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x64, 0x12, 0x0f, 0x0a, 0x0a, 0x44,
	0x49, 0x47, 0x45, 0x53, 0x54, 0x5f, 0x4d, 0x44, 0x35, 0x10, 0xc8, 0x01, 0x12, 0x12, 0x0a, 0x0d,
	0x44, 0x49, 0x47, 0x45, 0x53, 0x54, 0x5f, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x10, 0xac, 0x02,
	0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62,
	0x69, 0x6e, 0x61, 0x72, 0x6c, 0x79, 0x2d, 0x69, 0x6f, 0x2f, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_common_digest_proto_rawDescOnce sync.Once
	file_api_common_digest_proto_rawDescData = file_api_common_digest_proto_rawDesc
)

func file_api_common_digest_proto_rawDescGZIP() []byte {
	file_api_common_digest_proto_rawDescOnce.Do(func() {
		file_api_common_digest_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_common_digest_proto_rawDescData)
	})
	return file_api_common_digest_proto_rawDescData
}

var file_api_common_digest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_common_digest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_common_digest_proto_goTypes = []interface{}{
	(DigestType)(0), // 0: api.common.DigestType
	(*Digest)(nil),  // 1: api.common.Digest
}
var file_api_common_digest_proto_depIdxs = []int32{
	0, // 0: api.common.Digest.type:type_name -> api.common.DigestType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_common_digest_proto_init() }
func file_api_common_digest_proto_init() {
	if File_api_common_digest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_common_digest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Digest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_common_digest_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_digest_proto_goTypes,
		DependencyIndexes: file_api_common_digest_proto_depIdxs,
		EnumInfos:         file_api_common_digest_proto_enumTypes,
		MessageInfos:      file_api_common_digest_proto_msgTypes,
	}.Build()
	File_api_common_digest_proto = out.File
	file_api_common_digest_proto_rawDesc = nil
	file_api_common_digest_proto_goTypes = nil
	file_api_common_digest_proto_depIdxs = nil
}
