// Copyright The TBox Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// Metrics come from client to server in order to track client's activities.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: api/common/metrics.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricsType represents areas of metrics accumulation - such as resource utilization, etc
type MetricsType int32

const (
	// Due to first enum value has to be zero in proto3
	MetricsType_METRICS_TYPE_RESERVED MetricsType = 0
	// Unspecified means we do not know its type
	MetricsType_METRICS_TYPE_UNSPECIFIED MetricsType = 100
	// Resource utilization, such as CPU, RAM, etc
	MetricsType_METRICS_TYPE_RESOURCE_UTILIZATION MetricsType = 200
)

// Enum value maps for MetricsType.
var (
	MetricsType_name = map[int32]string{
		0:   "METRICS_TYPE_RESERVED",
		100: "METRICS_TYPE_UNSPECIFIED",
		200: "METRICS_TYPE_RESOURCE_UTILIZATION",
	}
	MetricsType_value = map[string]int32{
		"METRICS_TYPE_RESERVED":             0,
		"METRICS_TYPE_UNSPECIFIED":          100,
		"METRICS_TYPE_RESOURCE_UTILIZATION": 200,
	}
)

func (x MetricsType) Enum() *MetricsType {
	p := new(MetricsType)
	*p = x
	return p
}

func (MetricsType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_metrics_proto_enumTypes[0].Descriptor()
}

func (MetricsType) Type() protoreflect.EnumType {
	return &file_api_common_metrics_proto_enumTypes[0]
}

func (x MetricsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricsType.Descriptor instead.
func (MetricsType) EnumDescriptor() ([]byte, []int) {
	return file_api_common_metrics_proto_rawDescGZIP(), []int{0}
}

// Metrics is a set of Metric tuples.
// Metric can be classified either by type or by name.
// MetricType can be specified once for the whole set of metrics, instead of specifying in each one of them.
type Metrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Header represents metadata of the set of metrics
	Header *Metadata `protobuf:"bytes,100,opt,name=header,proto3" json:"header,omitempty"`
	// Optional. Type of metrics set.
	// Object can be typed/identified either by type or by name.
	Type *int32 `protobuf:"varint,200,opt,name=type,proto3,oneof" json:"type,omitempty"`
	// Optional. Name of metrics set.
	// Object can be typed/identified either by type or by name.
	Name *string `protobuf:"bytes,300,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Metrics is the purpose of the whole Metrics data type, is expected to be present at all time.
	Metrics []*Metric `protobuf:"bytes,400,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_common_metrics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_metrics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_api_common_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metrics) GetHeader() *Metadata {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Metrics) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *Metrics) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Metrics) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_api_common_metrics_proto protoreflect.FileDescriptor

var file_api_common_metrics_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x01, 0x0a, 0x07, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0xc8, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x18,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0xac, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x18, 0x90, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x07,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x2a, 0x6e, 0x0a, 0x0b, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x45, 0x54, 0x52,
	0x49, 0x43, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x45, 0x52, 0x56, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x4d, 0x45, 0x54, 0x52, 0x49, 0x43, 0x53, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x64, 0x12, 0x26, 0x0a, 0x21, 0x4d, 0x45, 0x54, 0x52, 0x49, 0x43, 0x53, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x55, 0x54, 0x49, 0x4c, 0x49,
	0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0xc8, 0x01, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x6c, 0x79, 0x2d,
	0x69, 0x6f, 0x2f, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_common_metrics_proto_rawDescOnce sync.Once
	file_api_common_metrics_proto_rawDescData = file_api_common_metrics_proto_rawDesc
)

func file_api_common_metrics_proto_rawDescGZIP() []byte {
	file_api_common_metrics_proto_rawDescOnce.Do(func() {
		file_api_common_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_common_metrics_proto_rawDescData)
	})
	return file_api_common_metrics_proto_rawDescData
}

var file_api_common_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_common_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_common_metrics_proto_goTypes = []interface{}{
	(MetricsType)(0), // 0: api.common.MetricsType
	(*Metrics)(nil),  // 1: api.common.Metrics
	(*Metadata)(nil), // 2: api.common.Metadata
	(*Metric)(nil),   // 3: api.common.Metric
}
var file_api_common_metrics_proto_depIdxs = []int32{
	2, // 0: api.common.Metrics.header:type_name -> api.common.Metadata
	3, // 1: api.common.Metrics.metrics:type_name -> api.common.Metric
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_common_metrics_proto_init() }
func file_api_common_metrics_proto_init() {
	if File_api_common_metrics_proto != nil {
		return
	}
	file_api_common_metadata_proto_init()
	file_api_common_metric_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_common_metrics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_common_metrics_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_common_metrics_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_metrics_proto_goTypes,
		DependencyIndexes: file_api_common_metrics_proto_depIdxs,
		EnumInfos:         file_api_common_metrics_proto_enumTypes,
		MessageInfos:      file_api_common_metrics_proto_msgTypes,
	}.Build()
	File_api_common_metrics_proto = out.File
	file_api_common_metrics_proto_rawDesc = nil
	file_api_common_metrics_proto_goTypes = nil
	file_api_common_metrics_proto_depIdxs = nil
}
