#!/bin/bash

CUR_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source "${CUR_DIR}/config.sh"

# May be todo something with volumes

NETWORK_NAME="${NETWORK_NAME}" \
VOLUMES_ROOT="${VOLUMES_ROOT}" \
MINIO_ROOT_USER="${MINIO_ROOT_USER}" \
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD}" \
MYSQL_DATABASE="${MYSQL_DATABASE}" \
MYSQL_USER="${MYSQL_USER}" \
MYSQL_PASSWORD="${MYSQL_PASSWORD}" \
MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}" \
POSTGRES_DB="${POSTGRES_DB}" \
POSTGRES_USER="${POSTGRES_USER}" \
POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
CLICKHOUSE_DATABASE="${CLICKHOUSE_DATABASE}" \
CLICKHOUSE_USER="${CLICKHOUSE_USER}" \
CLICKHOUSE_PASSWORD="${CLICKHOUSE_PASSWORD}" \
docker-compose \
    -f ./docker-compose.yaml \
    down \
    --remove-orphans
