#!/bin/bash

CUR_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
SRC_ROOT="$(realpath "${CUR_DIR}/../..")"

DOCKER_ROOT="${SRC_ROOT}/docker"

NETWORK_NAME="${NETWORK_NAME:-"tbox"}"
VOLUMES_ROOT="${VOLUMES_ROOT:-"${CUR_DIR}/volumes"}"
MINIO_ROOT_USER="${MINIO_ROOT_USER:-"minio1"}"
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-"minio123"}"
MYSQL_DATABASE="${MYSQL_DATABASE:-"tbox"}"
MYSQL_USER="${MYSQL_USER:-"user"}"
MYSQL_PASSWORD="${MYSQL_PASSWORD:-"qwerty"}"
MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-"qwerty"}"
POSTGRES_DB="${POSTGRES_DB:-"tbox"}"
POSTGRES_USER="${POSTGRES_USER:-"user"}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-"qwerty"}"
CLICKHOUSE_DATABASE="${CLICKHOUSE_DATABASE:-"tbox"}"
CLICKHOUSE_USER="${CLICKHOUSE_USER:-"user"}"
CLICKHOUSE_PASSWORD="${CLICKHOUSE_PASSWORD:-"qwerty"}"
